#===========================================================================
#
# This file is a part of the Rebuild Armbian
# https://github.com/ophub/amlogic-s9xxx-armbian
#
# LCKFB TaishanPi 3M RK3576 Board
#
#===========================================================================

# Set the kernel file adjustment command for a special board (fixed parameters)
adjust_kernel_files="yes"
adjust_kernel_files_cmd() {
    cp -f ${platform_files}/${PLATFORM}/bootfs/dtb/rockchip/rk3576-lckfb-tspi-3m.dtb \
          ${tag_bootfs}/dtb/rockchip/rk3576-lckfb-tspi-3m.dtb
}
